services:
  app:
    build: .
    container_name: go-dutch-app
    restart: always
    ports:
      - "${APP_GODUTCH_SERVERPORT}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: go-dutch-db
    restart: always
    environment:
      POSTGRES_USER: ${APP_GODUTCH_DBUSERNAME}
      POSTGRES_PASSWORD: ${APP_GODUTCH_DBPASSWORD}
      POSTGRES_DB: ${APP_GODUTCH_DBDEFAULTNAME}
    ports:
      - "${APP_GODUTCH_DBPORT}:5432"
    volumes:
      - local-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_GODUTCH_DBUSERNAME} -d ${APP_GODUTCH_DBDEFAULTNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  local-postgres:
